import Foundation
import AppKit
import UniformTypeIdentifiers

// MARK: - Image Asset Model

/// Observable model representing a single image file on disk.
///
/// `ImageAsset` is the central unit of the Lumina Forge library. It is created
/// immediately when a URL is discovered, populated lazily with a thumbnail
/// (via `ThumbnailActor`) and parsed metadata (via `MetadataActor`), and
/// observed by SwiftUI views through the `@Observable` macro.
///
/// Thread-safety note: `ImageAsset` is marked `@unchecked Sendable` because
/// `NSImage` is not `Sendable`. All mutations happen either:
/// - On the MainActor (SwiftUI-driven flag toggles), or
/// - From within an actor context that serialises access (MetadataActor /
///   ThumbnailActor).  Never mutate the same instance from two concurrent
///   contexts simultaneously.
@Observable
final class ImageAsset: Identifiable, @unchecked Sendable {

    // MARK: - Identity

    /// Stable unique identifier for use as a SwiftUI `Identifiable` key.
    let id: UUID

    /// Absolute file URL on disk.  Always valid; never mutated after init.
    let url: URL

    // MARK: - Loading State

    /// `true` once full metadata has been populated by `MetadataActor`.
    var isMetadataLoaded: Bool = false

    /// `true` once a thumbnail has been generated by `ThumbnailActor`.
    var isThumbnailLoaded: Bool = false

    // MARK: - User Interaction State

    /// Grid selection state (single or multi-select).
    var isSelected: Bool = false

    /// User-marked favourite.
    var isFavorite: Bool = false

    /// Queued for batch export.
    var isInExportQueue: Bool = false

    // MARK: - Payload

    /// Parsed EXIF / IPTC / XMP metadata; `nil` until `MetadataActor` fills it.
    var metadata: MetadataModel?

    /// Scaled thumbnail for display in the grid; `nil` until generated.
    var thumbnail: NSImage?

    /// User-applied free-form tags (stored locally; not written to file EXIF).
    var tags: [String]

    /// File size in bytes, cached on first load to avoid repeated `stat()` calls.
    var cachedFileSize: Int64?

    // MARK: - Initialiser

    init(
        id: UUID = UUID(),
        url: URL,
        tags: [String] = []
    ) {
        self.id   = id
        self.url  = url
        self.tags = tags
    }

    // MARK: - Computed Display Helpers

    /// The file's last path component (e.g. `IMG_4321.CR3`).
    var fileName: String { url.lastPathComponent }

    /// Lower-cased file extension (e.g. `"cr3"`, `"heic"`).
    var fileExtension: String { url.pathExtension.lowercased() }

    /// Human-readable file size using the system byte formatter.
    var formattedFileSize: String {
        let bytes = cachedFileSize ?? Self.diskFileSize(for: url)
        guard let bytes else { return "—" }
        return ByteCountFormatter.string(fromByteCount: bytes, countStyle: .file)
    }

    /// Pixel dimensions string, e.g. `"6000 × 4000 px"`.
    var formattedDimensions: String {
        guard let w = metadata?.imageWidth, let h = metadata?.imageHeight else { return "—" }
        return "\(w) × \(h) px"
    }

    /// Short date string derived from EXIF DateTimeOriginal.
    var formattedDate: String {
        guard let date = metadata?.dateTimeOriginal else { return "—" }
        return date.formatted(date: .abbreviated, time: .shortened)
    }

    /// Best available title: IPTC Title → file name.
    var displayTitle: String {
        metadata?.title?.nilIfEmpty ?? fileName
    }

    // MARK: - Static Helpers

    /// Reads the on-disk file size without caching.
    static func diskFileSize(for url: URL) -> Int64? {
        (try? url.resourceValues(forKeys: [.fileSizeKey]))?
            .fileSize
            .map(Int64.init)
    }
}

// MARK: - String Convenience

private extension String {
    /// Returns `nil` when the string is empty, otherwise `self`.
    var nilIfEmpty: String? { isEmpty ? nil : self }
}
